# Generated by Django 4.2.25 on 2025-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
                ),
                (
                    "bonus_won",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=38),
                ),
                ("name", models.CharField(max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=191, null=True)),
                ("last_name", models.CharField(blank=True, max_length=191, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=191, null=True)),
                ("unique_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "referrer_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "referred_by",
                    models.CharField(blank=True, max_length=191, null=True),
                ),
                ("phone_code", models.CharField(blank=True, max_length=100, null=True)),
                ("mobile", models.CharField(blank=True, max_length=100, null=True)),
                ("currency", models.CharField(blank=True, max_length=191, null=True)),
                ("info", models.CharField(blank=True, max_length=191, null=True)),
                ("token", models.CharField(blank=True, max_length=191, null=True)),
                ("new_token", models.CharField(blank=True, max_length=191, null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("SuperAdmin", "SuperAdmin"),
                            ("SubAdmin", "SubAdmin"),
                            ("User", "User"),
                            ("CSRAgent", "CSRAgent"),
                            ("DWAdmin", "DWAdmin"),
                            ("DWAgent", "DWAgent"),
                            ("MasterExternalAgent", "MasterExternalAgent"),
                            ("ExternalAgent", "ExternalAgent"),
                        ],
                        default="User",
                        max_length=50,
                    ),
                ),
                ("reg_type", models.CharField(max_length=191)),
                (
                    "block_user",
                    models.CharField(
                        choices=[("0", "Active"), ("1", "Blocked")],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("otp", models.IntegerField(default=0)),
                ("otp_verify", models.IntegerField()),
                ("password", models.CharField(blank=True, max_length=191, null=True)),
                ("designation_id", models.CharField(default="0", max_length=10000)),
                ("admin_id", models.CharField(blank=True, max_length=11, null=True)),
                ("agent_id", models.IntegerField(blank=True, null=True)),
                (
                    "agent_password",
                    models.CharField(blank=True, max_length=191, null=True),
                ),
                (
                    "remember_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profileimage",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telegram", models.CharField(blank=True, max_length=191, null=True)),
                ("instagram", models.CharField(blank=True, max_length=191, null=True)),
                (
                    "whatsapp_no",
                    models.CharField(blank=True, max_length=191, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "enteredbyid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("is_added_back_office", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("extra_info", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "master_external_agent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
    ]
