# Generated by Django 4.2.25 on 2025-10-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp_verify",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
