# Generated by Django 4.2.25 on 2025-10-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0003_blacklistedtoken_activetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklistedtoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
