# Generated by Django 4.2.25 on 2025-10-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0004_blacklistedtoken_expires_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="blacklistedtoken", name="user",),
        migrations.AddField(
            model_name="blacklistedtoken",
            name="user_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
